# Generated by Django 5.1.4 on 2025-02-26 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('price_range', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=120)),
                ('content', models.TextField(max_length=220, unique=True, verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=12, null=True)),
                ('bvn', models.CharField(blank=True, max_length=15, null=True)),
                ('active', models.BooleanField(default=False)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined'],
            },
        ),
        migrations.CreateModel(
            name='CryptoDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=25)),
                ('crypto', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('naira', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='deposit_screenshots/')),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Cart Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=25)),
                ('code', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('naira', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asap.categories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='giftcard_images/')),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='asap.giftcard')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('allow_notifications', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('pin', models.CharField(blank=True, max_length=4, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined'],
            },
        ),
    ]
