# Generated by Django 5.1.4 on 2025-02-26 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='crypto_logos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='code',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='naira',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='price',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='status',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='type',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftcard',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='giftcard_logos/'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='price_range',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='GiftCardDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Cart Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=25)),
                ('code', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('naira', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('giftcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asap.giftcard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
