# Generated by Django 5.1.4 on 2024-12-27 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0003_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
