# Generated by Django 5.1.4 on 2024-12-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
