# Generated by Django 5.1.4 on 2024-12-27 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0005_alter_profile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Giftcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Amazon', 'Amazon'), ('Steam', 'Steam'), ('Google Play', 'Google Play'), ('iTunes', 'iTunes'), ('Xbox', 'Xbox'), ('PlayStation', 'PlayStation'), ('Netflix', 'Netflix')], max_length=50, verbose_name='Cart Type')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Cart Code')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
