# Generated by Django 5.1.4 on 2024-12-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0007_alter_bank_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
