# Generated by Django 5.1.4 on 2024-12-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0008_remove_profile_email_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='mumu', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
