# Generated by Django 5.1.4 on 2024-12-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0009_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
