# Generated by Django 5.1.4 on 2025-01-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0011_crypto_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
