# Generated by Django 5.1.4 on 2025-01-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0012_bank_active_profile_allow_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
