# Generated by Django 5.1.4 on 2025-01-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0014_alter_bank_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
