# Generated by Django 5.1.4 on 2025-01-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0016_expodevice_delete_crypto_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True, verbose_name='Content')),
                ('price', models.PositiveIntegerField(default=1610)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(max_length=220, unique=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.TextField(max_length=120),
        ),
        migrations.DeleteModel(
            name='ExpoDevice',
        ),
    ]
